inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Max: 7
  Exclude:
    - "bin/bundle"
    - "db/migrate/*"
